{"name": "test_0", "status": "failed", "statusDetails": {"message": "AssertionError: assert 5050 == 5051", "trace": "def test_0():\n        #计算100以内的和\n        a = 0\n        for i in range(101):\n            a = a + i\n        #  预期结果是5050，\n        #  实际结果是a\n        #断言指的是：拿实际结果与预期结果进行对比的过程\n>       assert a == 5051\nE       assert 5050 == 5051\n\ntest_1.py:26: AssertionError"}, "start": 1565577343825, "stop": 1565577343825, "uuid": "cdace167-1dc4-43b7-90d8-cf6336cae8cb", "historyId": "debb69768f2f715cfcfa904ea07c89c1", "fullName": "test_1#test_0", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_1"}, {"name": "subSuite"}, {"name": "host", "value": "pc-guohonggang"}, {"name": "thread", "value": "5992-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_1"}]}