{"name": "test_three", "status": "failed", "statusDetails": {"message": "AssertionError: assert 100 < 10", "trace": "def test_three():\n        n = 100\n        # 设定断言，判断n小于101\n>       assert n < 10\nE       assert 100 < 10\n\ntest_2.py:25: AssertionError"}, "start": 1565593400092, "stop": 1565593400092, "uuid": "1b6119dd-491a-48af-8076-282f17afb71f", "historyId": "d92f26e0c8f8670fa59cb88baf223eba", "fullName": "test_2#test_three", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_2"}, {"name": "subSuite"}, {"name": "host", "value": "pc-guohonggang"}, {"name": "thread", "value": "10460-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_2"}]}