{"name": "test_2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'python' in 'hello pytest'", "trace": "def test_2():\n        str_1 = \"hello pytest\"\n        str_2 = \"python\"\n        # 设定断言，判断str_2 在 str_1内\n>       assert str_2 in str_1\nE       AssertionError: assert 'python' in 'hello pytest'\n\ntest_1.py:20: AssertionError"}, "start": 1565593400051, "stop": 1565593400052, "uuid": "db90f8b5-64f1-4ab3-bdcf-6c76c4a524d0", "historyId": "3d596e8527c418dee23485086c99e22a", "fullName": "test_1#test_2", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_1"}, {"name": "subSuite"}, {"name": "host", "value": "pc-guohonggang"}, {"name": "thread", "value": "10460-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_1"}]}