{"name": "test_2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'python' in 'hello pytest'", "trace": "def test_2():\n        str_1 = \"hello pytest\"\n        str_2 = \"python\"\n        # 设定断言，判断str_2 在 str_1内\n>       assert str_2 in str_1\nE       AssertionError: assert 'python' in 'hello pytest'\n\ntest_2.py:19: AssertionError"}, "start": 1565593400082, "stop": 1565593400082, "uuid": "2734badb-83a5-437d-8d00-16b56f135a30", "historyId": "c582a42fd310f1877e0de791e5abbe5d", "fullName": "test_2#test_2", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_2"}, {"name": "subSuite"}, {"name": "host", "value": "pc-guohonggang"}, {"name": "thread", "value": "10460-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_2"}]}