{"name": "test_1", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 2", "trace": "def test_1():\n        a = 1\n        b = 2\n        c = a + b\n        # 实际结果是3，预期结果是2\n        # 设定断言\n>       assert c == 2\nE       assert 3 == 2\n\nT1\\test_1.py:13: AssertionError"}, "start": 1565580339199, "stop": 1565580339199, "uuid": "98ff45ac-4306-415d-abee-cb8464b54170", "historyId": "4d0b2befaa03b519f58fcdb81cb9ea31", "fullName": "T1.test_1#test_1", "labels": [{"name": "parentSuite", "value": "T1"}, {"name": "suite", "value": "test_1"}, {"name": "subSuite"}, {"name": "host", "value": "pc-guohonggang"}, {"name": "thread", "value": "9692-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "T1.test_1"}]}