{"name": "test_three", "status": "failed", "statusDetails": {"message": "AssertionError: assert 100 < 10", "trace": "def test_three():\n        n = 100\n        # 设定断言，判断n小于101\n>       assert n < 10\nE       assert 100 < 10\n\nT1\\test_2.py:25: AssertionError"}, "start": 1565657740580, "stop": 1565657740580, "uuid": "b4e0b92a-b0dc-482c-a128-f169922d97b8", "historyId": "8664ad1bc4d7a6a38d644fc208461c32", "fullName": "T1.test_2#test_three", "labels": [{"name": "parentSuite", "value": "T1"}, {"name": "suite", "value": "test_2"}, {"name": "subSuite"}, {"name": "host", "value": "pc-guohonggang"}, {"name": "thread", "value": "11656-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "T1.test_2"}]}