{"name": "test_3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0 > 123213", "trace": "@allure.feature(\"模块二\")\n    @allure.story(\"这是一个很棒的测试用例\")\n    def test_3():\n>       assert  0 > 123213\nE       assert 0 > 123213\n\ntest_1.py:23: AssertionError"}, "start": 1566182361835, "stop": 1566182361835, "uuid": "c7ffd3c7-ffd7-432a-8c2f-19a71a3cb1c9", "historyId": "5573ca69ec5a612ab6ebd2e4e95d945e", "fullName": "test_1#test_3", "labels": [{"name": "feature", "value": "模块二"}, {"name": "story", "value": "这是一个很棒的测试用例"}, {"name": "parentSuite"}, {"name": "suite", "value": "test_1"}, {"name": "subSuite"}, {"name": "host", "value": "pc-guohonggang"}, {"name": "thread", "value": "4352-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_1"}]}